_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 14
                - 15
                - 16
                - 23
                - 55
            "4": 3.10.13
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
api_key:
    value: 014379c0f960b9d9a15741d328aa2c2a0f3a6478
batch_size:
    value: 64
model_name:
    value: movie_predictor
next_run_name:
    value: movie-predictor-003
num_epochs:
    value: 10
project_name:
    value: movie-predictor
run_name:
    value: movie-predictor-002
